default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: homeless-app_development

test:
  <<: *default
  database: homeless-app_test

production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: <%= ENV['DATABASE_URL'] %>
